title: Rahul Kalluri
theme: charlolamode

menu:
    main:
        - name: Projects
          url: /projects/
          weight: 40
        - name: About
          url: /about/
          weight: 20

params:
  author: Rahul Kalluri

  defaultTheme: dark
  disableThemeToggle: false

  profileMode:
      # Disable to populate home page with 'mainSections' content
      enabled: true
      title: Hello there, visitor 👋
              
              
              I'm Rahul
      description: You could say I like data. 


              I also work for IBM as a Data Scientist + Machine Learning Engineer.
      imageUrl: "/images/profile.png"
      imageTitle: my image
  socialIcons:
      - name: github
        url: "https://github.com/rahulkalluri"
      - name: linkedin
        url: "https://www.linkedin.com/in/rahulkalluri/"
      - name: buymeacoffee
        url: "https://ko-fi.com/rahulkalluri"
  # change favicon in images folder (icon for web tab)
  assets:
        favicon: "/images/favicon.ico"
        favicon16x16: "/images/favicon-16x16.png"
        favicon32x32: "/images/favicon-32x32.png"
        apple_touch_icon: "/images/apple-touch-icon.png"
        safari_pinned_tab: "/images/apple-touch-icon.png"


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true